### ISSUE TITLE
Is it possible to hook travis up to a custom test script?

### ISSUE THREAD

**Issue by jackcarlisle** [dwyl/adoro#49]
Our pre-build tests are failing because travis is running npm test (related to master), whereas we have written our own custom 'npm run tapetest' script for tests on our own branch. Is it possible to configure travis in such a way that it runs a script of your choice for a specific branch?

**Comment by nelsonic** [comment]
@jackcarlisle yes, you can. https://docs.travis-ci.com/user/customizing-the-build/
in your case you can simply set your test script in `package.json` to:
```js
"test": "npm run tapetest && ./node_modules/.bin/istanbul cover ./node_modules/tape/bin/tape ./test/*.test.js"
```
if you get stuck let me know.

**Comment by jackcarlisle** [comment]
@nelsonic Thank you!
