### ISSUE TITLE
Readme Composition

### ISSUE THREAD

**Issue by rug1** [dwyl/adoro#55]
Adding Walkthrough section with @hdrdavies

**Comment by rug1** [comment]
This has been done in the last pull request

**Comment by iteles** [comment]
@rug1 Worth noting that when someone comes back to read this, they won't know what 'the last pull request' is referring to. You can link these easily in the same way you've done with the issue in the commit message :clap:

**Comment by rug1** [comment]
@iteles ok thanks, I'll remember for next time
