### ISSUE TITLE
Too many branches

### ISSUE THREAD

**Issue by hdrdavies** [dwyl/adoro#77]
![image](https://cloud.githubusercontent.com/assets/13098199/11588301/41aa5f84-9a77-11e5-97d0-816861b11e8e.png)

ouch....

**Comment by nelsonic** [comment]
I'm sure there is still work going on in *all* of them... :wink: 
(*we can prune at the end of the sprint*...)

**Comment by Jbarget** [comment]
@hdrdavies sorted?

**Comment by hdrdavies** [comment]
Lovely
