### ISSUE TITLE
BLCRS console.logs to delete

### ISSUE THREAD

**Issue by thegsi** [dwyl/adoro#80]
https://github.com/dwyl/adoro/blob/BLCRS/public/editor.js#L9
https://github.com/dwyl/adoro/blob/BLCRS/public/editor.js#L9
https://github.com/dwyl/adoro/blob/BLCRS/public/editor.js#L11

Commented out
https://github.com/dwyl/adoro/blob/BLCRS/public/editor.js#L11
https://github.com/dwyl/adoro/blob/BLCRS/public/editor.js#L11

**Comment by thegsi** [comment]
Not sure if some of these were in the file to begin with? Sorry if so,

**Comment by tormod17** [comment]
Editors.js has now been  updated and we have removed all console logs , cheers

**Comment by hdrdavies** [comment]
Ta @thegsi :+1:
