### ISSUE TITLE
Where next?

### ISSUE THREAD

**Issue by des-des** [dwyl/adoro#89]
#### What we have

What were have after that [last merge](https://github.com/dwyl/adoro/pull/85) is pretty basic.
##### creating the site:
 * convert all the markdown in a particular file to html
 * find all the image urls
 * download all the images and find their dimensions
 * replace `img` tags with `amp-img` tags, with dimensions specified
 * plug this html into handlebars to create amp complient website
 * save everything to file system

##### serving the site
 * continuous deployment to to heroku
 * hapi server on heroku serving up bloging site

#### first problems
 - [ ] merging other [pull request](https://github.com/dwyl/adoro/pull/87). What is here that would be of use?
 - [ ] quick pass at styling so it does not look so bad
 - [ ] Save download images / dimensions to db (downloading them for every build is very inefficient)

#### where next
 * How do we package this up in a nice way? Is it doing (or going to do) too much to be an npm module?
 * Who is the user?? Is the content manager (assuming non technical) going to be inputting content in markdown?
 * Do we need a way to add more control over content than markdown? ie should the user have the ability to format an image (float right etc..) can we do this by specifing some extra rules for our md?
 * is the file system the best place to store the compiled site? maybe redis or local variables is better?

**Comment by nelsonic** [comment]
@des-des we need to white-board this with whoever else is interested in moving it forward.
I have a couple of ideas but I know other people will have loads more. when are you free? :wink:

**Comment by des-des** [comment]
@nelsonic I can do monday 4th late afternoon?

**Comment by nelsonic** [comment]
@des-des sounds good lets say *evening* then (*provisionally*) :+1:

**Comment by des-des** [comment]
:+1:

**Comment by nelsonic** [comment]
@des-des if you have time to fix the merge conflict on the other PR please have a look. thanks.
